Repository 1Hive/gardens-ui, pull requests merged in 2020-10, with the labels that each got.

#108 App reestructure
  package.json
  src/App.js
  src/Routes.js
  src/app-logic.js
  src/assets/lotties/bee-animation.json
  src/components/Feed/EmptyResults.js
  src/components/Feed/MainScreen.js
  src/components/Feed/ProposalDetail.js
  src/components/Feed/Proposals.js
  src/components/Feed/ProposalsList.js
  src/components/Loader.js
  src/components/MainView.js
  src/components/Profile/Activity.js
  src/components/ProposalDetail/ProposalActions.js
  src/constants.js
  src/hooks/useEffectiveSupply.js
  src/hooks/useFilterProposals.js
  src/hooks/useOrgHooks.js
  src/hooks/useProposalFilters.js
  src/hooks/useProposals.js
  src/hooks/useStakes.js
  src/hooks/useSubscriptions.js
  src/lib/conviction.js
  src/lib/data-utils.js
  src/lib/proposal-utils.js
  src/logic/app-logic.js
  src/logic/proposal-logic.js
  src/providers/AppState.js
  src/screens/Feed.js
  src/screens/Home.js
  src/screens/ProposalDetail.js
  src/types.js
  src/utils/filter-utils.js
  yarn.lock
Labels: V2

#109 Feed
  src/assets/banner-mobile.png
  src/assets/banner-tablet.png
  src/assets/banner.png
  src/assets/rankings/ranking-best-selected.svg
  src/assets/rankings/ranking-best.svg
  src/assets/rankings/ranking-hot-selected.svg
  src/assets/rankings/ranking-hot.svg
  src/assets/rankings/ranking-new-selected.svg
  src/assets/rankings/ranking-new.svg
  src/assets/rankings/ranking-top-selected.svg
  src/assets/rankings/ranking-top.svg
  src/components/BalanceModule.js
  src/components/Feed/HeroBanner.js
  src/components/Feed/ProposalCard.js
  src/components/Feed/ProposalCreator.js
  src/components/Feed/ProposalFooter.js
  src/components/Feed/ProposalHeader.js
  src/components/Feed/ProposalRankings.js
  src/components/Feed/ProposalSupport.js
  src/components/Feed/ProposalsList.js
  src/components/FilterSidebar/FilterSidebar.js
  src/components/FilterSidebar/ListFilter.js
  src/components/FilterSidebar/TextFilter.js
  src/components/Header/Header.js
  src/components/Icons.js
  src/components/IdentityBadge.js
  src/components/ProposalIcon.js
  src/components/SupportersDistribution.js
  src/components/Wallet.js
  src/endpoints.js
  src/hooks/useAccountTokens.js
  src/screens/Home.js
Labels: V2

#119 Sort based on staked HNY
  src/screens/Proposals.js
Labels: bug

#125 Cache selected filters
  src/hooks/useProposalFilters.js
  src/utils/filter-utils.js
Labels: bug, v2

#131 Supporter distribution: Add missing amount to rest calculation
  src/lib/math-utils.js
Labels: bug, v2

#127 Conviction: Show pct with decimals
  src/components/ConvictionVisuals.js
Labels: v2

#130 Account module: Update profile button
  src/assets/profileButton.svg
  src/components/Account/AccountModule.js
  src/components/Account/ScreenConnected.js
Labels: v2

#120 Sort proposals by current conviction
  src/hooks/useProposals.js
  src/utils/filter-utils.js
Labels: v2

#113 V2: New feed fixes
  src/assets/profileButton.svg
  src/components/Account/AccountModule.js
  src/components/Account/ScreenConnected.js
  src/components/BalanceToken.js
  src/components/ConvictionVisuals.js
  src/components/FilterBar/DropdownFilter.js
  src/components/FilterBar/FilterBar.js
  src/components/FilterBar/TextFilter.js
  src/components/FilterSidebar/FilterSidebar.js
  src/components/Footer.js
  src/components/IdentityBadge.js
  src/components/Layout.js
  src/components/MainView.js
  src/components/Profile/Activity.js
  src/components/Profile/EditProfile.js
  src/components/SupportersDistribution.js
  src/components/panels/AddProposalPanel.js
  src/components/panels/SupportProposalPanel.js
  src/hooks/useAccountTotalStaked.js
  src/hooks/useActions.js
  src/hooks/useConvictionHistory.js
  src/hooks/useProposalFilters.js
  src/hooks/useProposals.js
  src/hooks/useSelectedProposal.js
  src/lib/data-utils.js
  src/lib/math-utils.js
  src/lib/search-utils.js
  src/providers/Profile.js
  src/screens/Home.js
  src/screens/Profile.js
  src/styles/breakpoints.js
  src/utils/date-utils.js
  src/utils/filter-utils.js
  yarn.lock
Labels: v2

#121 V2: Metrics
  package.json
  src/components/Feed/ProposalRankings.js
  src/components/Feed/ProposalsList.js
  src/components/FilterSidebar/FilterSidebar.js
  src/components/Metrics.js
  src/hooks/useUniswapHNYPrice.js
  src/logic/app-logic.js
  src/screens/Home.js
  yarn.lock
Labels: v2

#123 Responsive
  src/assets/arrowDown.svg
  src/assets/create.svg
  src/assets/filter.svg
  src/assets/getHoney.svg
  src/assets/home.svg
  src/components/Feed/HeroBanner.js
  src/components/Feed/ProposalCard.js
  src/components/Feed/ProposalCreator.js
  src/components/Feed/ProposalHeader.js
  src/components/Feed/ProposalRankings.js
  src/components/Feed/ProposalsList.js
  src/components/FilterSidebar/FilterSidebar.js
  src/components/Filters/CompactFilter.js
  src/components/Filters/Filters.js
  src/components/Filters/ListFilter.js
  src/components/Filters/TextFilter.js
  src/components/Footer.js
  src/components/Header/Header.js
  src/components/IdentityBadge.js
  src/components/Layout.js
  src/components/MainView.js
  src/components/Profile/Activity.js
  src/components/Profile/EditProfile.js
  src/components/Profile/MainProfile.js
  src/components/ProposalIcon.js
  src/screens/Home.js
  src/screens/Profile.js
  src/screens/ProposalDetail.js
  src/styles/breakpoints.js
Labels: v2

#76 Subgraph
  subgraph/.eslintrc
  subgraph/.gitignore
  subgraph/LICENSE
  subgraph/README.md
  subgraph/abis/ConvictionVoting.json
  subgraph/abis/DandelionVoting.json
  subgraph/abis/Kernel.json
  subgraph/abis/MiniMeToken.json
  subgraph/manifest/data/mainnet.json
  subgraph/manifest/data/rinkeby.json
  subgraph/manifest/data/xdai.json
  subgraph/manifest/templates/ConvictionVoting.template.yaml
  subgraph/manifest/templates/DandelionVoting.template.yaml
  subgraph/manifest/templates/Organization.template.yaml
  subgraph/package.json
  subgraph/schema.graphql
  subgraph/scripts/build-graph.sh
  subgraph/scripts/build-manifest.sh
  subgraph/scripts/codegen.sh
  subgraph/scripts/deploy.sh
  subgraph/src/ConvictionVoting.ts
  subgraph/src/DandelionVoting.ts
  subgraph/src/helpers/conviction.ts
  subgraph/src/helpers/index.ts
  subgraph/src/helpers/voting.ts
  subgraph/src/kernel.ts
  subgraph/src/statuses.ts
  subgraph/src/types.ts
  subgraph/subgraph.template.yaml
  subgraph/yarn.lock
Labels: v2

#102 BrightId verification
  package.json
  src/assets/verifiedCheck.svg
  src/components/LoadingRing.js
  src/components/Profile/BrightIdModal.js
  src/components/Profile/BrightIdStatus.js
  src/components/Profile/ProfileForm.js
  src/constants.js
  src/endpoints.js
  src/hooks/useBrightIdVerification.js
  src/services/brightIdResponseCodes.js
  src/services/sponsorUser.js
  yarn.lock
Labels: v2
