Repository 1Hive/gardens-ui, pull requests merged in 2020-09, with the labels that each got.

#64 V2: Main profile
  .gitignore
  package.json
  public/favicon.svg
  public/index.html
  src/assets/github.svg
  src/assets/twitter.svg
  src/components/Account/AccountButton.js
  src/components/Profile/Activity.js
  src/components/Profile/EditProfile.js
  src/components/Profile/MainProfile.js
  src/components/Profile/ProfileForm.js
  src/components/Profile/ProposalSupporting.js
  src/components/Profile/StakesManagment.js
  src/components/Profile/Tab.js
  src/components/Profile/Tabs.js
  src/components/SingleDatePicker/DatePicker.js
  src/components/SingleDatePicker/Labels.js
  src/components/SingleDatePicker/MonthDay.js
  src/components/SingleDatePicker/SingleDatePicker.js
  src/components/SingleDatePicker/components.js
  src/components/SingleDatePicker/consts.js
  src/components/SingleDatePicker/utils.js
  src/components/Wallet.js
  src/endpoints.js
  src/lib/profile.js
  src/providers/Profile.js
  src/screens/Profile.js
  src/utils/date-utils.js
  src/utils/validate-utils.js
  yarn.lock
Labels: V2

#67 V2 Identity badge: Add 3box profile name
  src/components/IdentityBadge.js
  src/components/SupportersDistribution.js
Labels: V2

#65 V2: Profile activity
  src/app-logic.js
  src/components/Profile/Activity.js
  src/components/Profile/ProposalSupporting.js
  src/components/Profile/StakesManagment.js
  src/components/Profile/StakingTokens.js
  src/components/Wallet.js
  src/hooks/useStakes.js
  src/providers/Profile.js
  src/screens/Feed.js
  src/screens/Profile.js
Labels: V2

#66 V2: New header
  src/assets/logo.svg
  src/assets/profileHeader.svg
  src/components/Account/AccountModule.js
  src/components/Account/ScreenConnected.js
  src/components/Account/ScreenProviders.js
  src/components/BalanceModule.js
  src/components/Header.js
  src/components/Header/Header.js
  src/components/Header/HeaderModule.js
  src/components/Header/HeaderPopover.js
  src/components/MainView.js
  src/components/Profile/MainProfile.js
  src/components/Profile/ProfileForm.js
  src/lib/token-utils.js
  src/providers/Profile.js
  src/screens/Feed.js
  src/screens/Profile.js
Labels: V2

#69 V2 Explore profiles
  src/app-logic.js
  src/components/BalanceModule.js
  src/components/Profile/Activity.js
  src/components/Profile/EditProfile.js
  src/components/Profile/MainProfile.js
  src/components/Profile/ProfileForm.js
  src/components/Wallet.js
  src/hooks/useSelectedProfile.js
  src/hooks/useStakes.js
  src/providers/Profile.js
  src/screens/Profile.js
Labels: V2

#82 Remove unused 2nd parameter on `executeProposal`
  src/hooks/useActions.js
Labels: bug

#86 Link to Discord instead of Keybase
  src/components/Footer.js
Labels: enhancement

#88 Title case title
  src/index.html
Labels: enhancement
