Repository 1Hive/gardens-ui, pull requests merged in 2022-01, with the labels that each got.

#802 Config: include fixed template addresses
  src/networks.js
Labels: 🩹 fix

#775 Fix/gh issue
  .env.example
  src/environment.js
  src/services/github.ts
  src/services/pinata.ts
Labels: 🐛bug, 🗺 epic

#800 UX: update header
  src/components/LandingBanner.tsx
Labels: 🩹 fix

#812 Feature: Script Check Env
  .env.example
  README.md
  package.json
  scripts/check_env.ts
  scripts/read-env-file.ts
  scripts/tsconfig.json
  yarn.lock
Labels: 👷‍♀️ DX, 📕 docs

#813 [Feature] Add Discord url pattern to forumURL at Create Proposal
  package.json
  src/components/Garden/ModalFlows/CreateProposalScreens/AddProposal.js
  src/utils/__tests__/regex-utils.test.ts
  src/utils/regex-utils.ts
  yarn.lock
Labels: 🙋‍♂️ request, ✨ feature
